name: Generate Profile Stat Cards

on:
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: StephenJarso
          theme: github_dark
          card_width: 550
        # available card types this action generates into the output branch:
        #   profile-details, repos-per-language, most-commit-language,
        #   stats, productive-time
